/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.view.components;

import application.view.color.SystemColor;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author PC
 */
public class MonthPicker extends javax.swing.JPanel {

    /**
     * Creates new form MonthPicker
     */
    private Calendar selectMonth;
    private Calendar today;

    public MonthPicker() {
        today = new GregorianCalendar();
        selectMonth = today;
        initComponents();
        showMonth();
    }

    private void showMonth() {
        SimpleDateFormat format = new SimpleDateFormat("MMMM yyyy");
        this.showMoth.setText(format.format(selectMonth.getTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showMoth = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        showMoth.setBackground(SystemColor.COLOR_3);
        showMoth.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        showMoth.setForeground(SystemColor.COLOR_5);
        showMoth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showMoth.setText("Tháng 6 2022");
        showMoth.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 4, 0, 4));
        showMoth.setPreferredSize(new java.awt.Dimension(160, 32));
        add(showMoth, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void previusMonth() {
        int month = selectMonth.get(Calendar.MONTH);
        int year = selectMonth.get(Calendar.YEAR);
        month--;
        if (month < Calendar.JANUARY) {
            year--;
            month = Calendar.DECEMBER;
        }
        selectMonth = new GregorianCalendar(year, month, 1);
        showMonth();
    }

    public void nextMonth() {
        int month = selectMonth.get(Calendar.MONTH);
        int year = selectMonth.get(Calendar.YEAR);
        month++;
        if (month > Calendar.DECEMBER) {
            year++;
            month = Calendar.JANUARY;
        }
        selectMonth = new GregorianCalendar(year, month, 1);
        showMonth();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel showMoth;
    // End of variables declaration//GEN-END:variables

    public Date getMonth() {
        return selectMonth.getTime();
    }
}
