/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.view.pane;

import application.view.color.SystemColor;
import application.view.components.transitionpane.TransitionsForm;

/**
 *
 * @author PC
 */
public class WellcomePane extends TransitionsForm {

    /**
     * Creates new form UserPane
     */
    public WellcomePane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        application.view.components.roundpane.RoundPanel roundPanel1 = new application.view.components.roundpane.RoundPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        application.view.components.card.LabelIcon labelIcon2 = new application.view.components.card.LabelIcon();
        application.view.components.card.LabelIcon labelIcon4 = new application.view.components.card.LabelIcon();
        application.view.components.card.LabelIcon labelIcon5 = new application.view.components.card.LabelIcon();
        application.view.components.card.LabelIcon labelIcon3 = new application.view.components.card.LabelIcon();
        application.view.components.card.LabelIcon labelIcon7 = new application.view.components.card.LabelIcon();
        application.view.components.card.LabelIcon labelIcon6 = new application.view.components.card.LabelIcon();
        application.view.components.card.LabelIcon labelIcon8 = new application.view.components.card.LabelIcon();
        application.view.components.card.LabelIcon labelIcon9 = new application.view.components.card.LabelIcon();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();

        setBackground(SystemColor.COLOR_1);
        setLayout(null);

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel1.setPreferredSize(new java.awt.Dimension(72, 72));
        roundPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Oswald", 1, 64)); // NOI18N
        jLabel1.setForeground(SystemColor.COLOR_4);
        jLabel1.setText("Quản Lý Chi Tiêu");
        roundPanel1.add(jLabel1);
        jLabel1.setBounds(40, 20, 520, 130);

        jPanel1.setOpaque(false);

        labelIcon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/view/icon/icons8_house_48px.png"))); // NOI18N
        labelIcon2.setPreferredSize(new java.awt.Dimension(72, 72));

        labelIcon4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/view/icon/icons8_food_48px.png"))); // NOI18N
        labelIcon4.setPreferredSize(new java.awt.Dimension(72, 72));

        labelIcon5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/view/icon/icons8_martini_glass_48px.png"))); // NOI18N
        labelIcon5.setPreferredSize(new java.awt.Dimension(72, 72));

        labelIcon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/view/icon/icons8_movie_48px.png"))); // NOI18N
        labelIcon3.setPreferredSize(new java.awt.Dimension(72, 72));

        labelIcon7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIcon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/view/icon/icons8_gasoline_refill_48px.png"))); // NOI18N
        labelIcon7.setPreferredSize(new java.awt.Dimension(72, 72));

        labelIcon6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/view/icon/icons8_shopping_bag_48px.png"))); // NOI18N
        labelIcon6.setPreferredSize(new java.awt.Dimension(72, 72));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelIcon4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIcon6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIcon7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelIcon5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelIcon4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelIcon7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIcon2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIcon3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIcon6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        roundPanel1.add(jPanel1);
        jPanel1.setBounds(170, 210, 420, 230);

        labelIcon8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIcon8.setPreferredSize(new java.awt.Dimension(64, 64));
        roundPanel1.add(labelIcon8);
        labelIcon8.setBounds(100, 140, 1000, 2);

        labelIcon9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIcon9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/view/icon/icons8_Dollar_Coin_240px.png"))); // NOI18N
        labelIcon9.setPreferredSize(new java.awt.Dimension(72, 72));
        roundPanel1.add(labelIcon9);
        labelIcon9.setBounds(720, 200, 260, 260);
        labelIcon9.setRadius(260);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/view/icon/icons8_card_payment_64px_2.png"))); // NOI18N
        roundPanel1.add(jLabel2);
        jLabel2.setBounds(1030, 90, 70, 50);

        add(roundPanel1);
        roundPanel1.setBounds(30, 50, 1180, 540);
        roundPanel1.setRound(20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
